name: MacOS build

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: stable

      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test --coverage -d macos integration_test

      - name: Remove generated files from coverage report
        run: |
          dart pub global activate remove_from_coverage
          dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info


  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: test

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: stable
      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build macos

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/macos/Build/Products/Release/handnote.app
