name: MacOS build

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: stable

      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test --coverage -d macos integration_test

      - name: Remove generated files from coverage report
        run: |
          dart pub global activate remove_from_coverage
          dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info


  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: test

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: stable
      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build macos

      - name: Create dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg
          RELEASE_PATH=build/macos/Build/Products/Release
          create-dmg \
            --volname Handnote \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \  
            --text-size 14 \  
            --icon "$RELEASE_PATH/handnote.app" 260 250 \
            --hide-extension "$RELEASE_PATH/handnote.app" \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            "$RELEASE_PATH/handnote.dmg" \
            "$RELEASE_PATH/handnote.app"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: build/macos/Build/Products/Release/handnote.dmg
