name: Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.x'
          channel: stable

      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test --coverage -d macos integration_test

      - name: Remove generated files from coverage report
        run: |
          dart pub global activate remove_from_coverage
          dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
