name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.x'
          channel: stable

      - run: flutter --version

      - run: flutter config --enable-macos-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Test
        run: flutter test --coverage -d macos integration_test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
